import { apiRequest } from './client.js'

export const api = {
  dashboard: (role) => apiRequest(`/dashboard/${role}`),
  warehouses: () => apiRequest('/warehouses'),
  warehouse: (id) => apiRequest(`/warehouses/${id}`),
  createWarehouse: (body) => apiRequest('/warehouses', { method: 'POST', body: JSON.stringify(body) }),
  products: () => apiRequest('/products'),
  createProduct: (body) => apiRequest('/products', { method: 'POST', body: JSON.stringify(body) }),
  sellers: () => apiRequest('/sellers'),
  createSeller: (body) => apiRequest('/sellers', { method: 'POST', body: JSON.stringify(body) }),
  users: () => apiRequest('/users'),
  createUser: (body) => apiRequest('/users', { method: 'POST', body: JSON.stringify(body) }),
  inventory: (query = '') => apiRequest(`/inventory${query}`),
  adjustInventory: (body) => apiRequest('/inventory/adjust', { method: 'POST', body: JSON.stringify(body) }),
  shipments: () => apiRequest('/inbound/shipments'),
  createShipment: (body) => apiRequest('/inbound/shipments', { method: 'POST', body: JSON.stringify(body) }),
  lookupShipment: (body) => apiRequest('/inbound/shipments/lookup', { method: 'POST', body: JSON.stringify(body) }),
  completeShipment: (id, body) => apiRequest(`/inbound/shipments/${id}/complete`, { method: 'POST', body: JSON.stringify(body) }),
  damageReports: () => apiRequest('/damage-reports'),
  resolveDamage: (id, resolution) => apiRequest(`/damage-reports/${id}/resolve`, { method: 'POST', body: JSON.stringify({ resolution }) }),
  orders: () => apiRequest('/orders'),
  createOrder: (body) => apiRequest('/orders', { method: 'POST', body: JSON.stringify(body) }),
  assignOrder: (id, warehouseId) => apiRequest(`/orders/${id}/assign-warehouse`, { method: 'POST', body: JSON.stringify({ warehouse_id: warehouseId }) }),
  transitionOrder: (id, action, body) => apiRequest(`/orders/${id}/${action}`, { method: 'POST', body: body ? JSON.stringify(body) : undefined }),
  packOrder: (id, body) => apiRequest(`/orders/${id}/pack`, { method: 'POST', body: JSON.stringify(body) }),
  generateLabel: (id) => apiRequest(`/packages/${id}/generate-label`, { method: 'POST' }),
  label: (id) => apiRequest(`/packages/${id}/label`),
  shipPackage: (id) => apiRequest(`/packages/${id}/ship`, { method: 'POST' }),
  cancelOrder: (id) => apiRequest(`/orders/${id}/cancel`, { method: 'POST' }),
  rejectOrder: (id) => apiRequest(`/orders/${id}/reject`, { method: 'POST', body: JSON.stringify({ reason: 'INSUFFICIENT_STOCK' }) }),
  createDamage: (shipmentId, body) => apiRequest(`/inbound/shipments/${shipmentId}/damage`, { method: 'POST', body: JSON.stringify(body) }),
  auditLogs: () => apiRequest('/audit-logs'),
  transactions: () => apiRequest('/inventory-transactions'),
  search: (query) => apiRequest(`/search?q=${encodeURIComponent(query)}`),
  pendingApprovals: () => apiRequest('/approvals/pending'),
  approveRegistration: (id) => apiRequest(`/approvals/${id}/approve`, { method: 'POST' }),
  rejectRegistration: (id, reason) => apiRequest(`/approvals/${id}/reject`, { method: 'POST', body: JSON.stringify({ reason }) }),
  issues: () => apiRequest('/issues'),
  createIssue: (body) => apiRequest('/issues', { method: 'POST', body: JSON.stringify(body) }),
  resolveIssue: (id, body) => apiRequest(`/issues/${id}/resolve`, { method: 'POST', body: JSON.stringify(body) }),
}
