import { Camera, Images } from 'lucide-react'
import { useRef, useState } from 'react'
import { api } from '../api/domain.js'
import DataTable from '../components/DataTable.jsx'
import Modal from '../components/Modal.jsx'
import PageHeader from '../components/PageHeader.jsx'
import StatusBadge from '../components/StatusBadge.jsx'
import { useAuth } from '../context/AuthContext.jsx'
import { useApi } from '../hooks/useApi.js'

export default function DamageReportsPage() {
  const { user } = useAuth(); const { data, loading, error, reload } = useApi(api.damageReports, []); const reports = Array.isArray(data) ? data : []; const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [viewer, setViewer] = useState(null); const fileInput = useRef(null)
  async function resolve(row, resolution) { setMessage(''); try { await api.resolveDamage(row.id, resolution); reload() } catch (requestError) { setMessage(requestError.message) } }
  async function upload(row, file) { if (!file) return; setBusy(true); setMessage(''); try { await api.uploadDamageImage(row.id, file); setMessage(`Photo evidence attached to ${row.damage_report_id}. Managers can now review it.`); reload() } catch (requestError) { setMessage(requestError.message) } finally { setBusy(false); fileInput.current.value = '' } }
  const columns = [{ key: 'damage_report_id', label: 'Report ID' }, { key: 'shipment_id', label: 'Shipment' }, { key: 'sku', label: 'SKU' }, { key: 'damage_quantity', label: 'Quantity' }, { key: 'damage_type', label: 'Type' }, { key: 'damage_reason', label: 'Reason' }, { key: 'image_urls', label: 'Evidence', render: (urls) => urls?.length ? <button onClick={() => setViewer(urls)} className="inline-flex items-center gap-1 font-semibold text-blue-600"><Images className="h-4 w-4" /> {urls.length} photo{urls.length > 1 ? 's' : ''}</button> : <span className="text-slate-400">No photo</span> }, { key: 'resolution_status', label: 'Status', render: (value) => <StatusBadge value={value} /> }]
  function actions(row) { return <div className="flex flex-wrap gap-2">{user.role === 'INBOUND' && row.resolution_status === 'OPEN' && <label className="cursor-pointer rounded-lg border border-blue-200 px-2 py-1.5 text-xs font-semibold text-blue-700"><Camera className="mr-1 inline h-3.5 w-3.5" />{busy ? 'Uploading…' : 'Add photo'}<input ref={fileInput} className="hidden" type="file" accept="image/*" onChange={(event) => upload(row, event.target.files?.[0])} /></label>}{['OWNER', 'MANAGER'].includes(user.role) && row.resolution_status === 'OPEN' && <select onChange={(event) => event.target.value && resolve(row, event.target.value)} defaultValue="" className="rounded-lg border border-slate-300 p-2 text-xs"><option value="">Decide…</option><option value="RETURN_TO_SUPPLIER">Return</option><option value="DISPOSE">Dispose</option><option value="MOVE_TO_GOOD_STOCK">Move to good</option><option value="KEEP_QUARANTINED">Keep quarantined</option></select>}</div> }
  return <><PageHeader eyebrow="Quality control" title="Damage reports" description="Inbound employees attach photo evidence. Managers review the evidence before deciding the final disposition." />{(error || message) && <p className={`mb-4 rounded-xl p-4 text-sm ${error || message.includes('failed') ? 'bg-red-50 text-red-700' : 'bg-emerald-50 text-emerald-800'}`}>{error || message}</p>}<DataTable rows={reports} empty={loading ? 'Loading reports…' : 'No damage reports'} columns={columns} actions={actions} /><Modal title="Damage photo evidence" open={Boolean(viewer)} onClose={() => setViewer(null)}><div className="grid gap-4 sm:grid-cols-2">{viewer?.map((url) => <a key={url} href={url} target="_blank" rel="noreferrer"><img src={url} alt="Damage evidence" className="aspect-square w-full rounded-xl border border-slate-200 object-cover" /></a>)}</div></Modal></>
}
