import { Plus } from 'lucide-react'
import { useState } from 'react'
import { api } from '../api/domain.js'
import DataTable from '../components/DataTable.jsx'
import { Field, Select, SubmitButton } from '../components/FormFields.jsx'
import Modal from '../components/Modal.jsx'
import PageHeader from '../components/PageHeader.jsx'
import StatusBadge from '../components/StatusBadge.jsx'
import { useAuth } from '../context/AuthContext.jsx'
import { useApi } from '../hooks/useApi.js'

const initial = { first_name: '', last_name: '', email: '', mobile: '', password: '', role: '', warehouse_id: '' }
export default function EmployeesPage() {
  const { user } = useAuth(); const { data: teamData, loading, error, reload } = useApi(api.users, []); const { data: warehouseData } = useApi(api.warehouses, []); const data = Array.isArray(teamData) ? teamData : []; const warehouses = Array.isArray(warehouseData) ? warehouseData : []; const [open, setOpen] = useState(false); const [form, setForm] = useState(initial); const [busy, setBusy] = useState(false); const [formError, setFormError] = useState('')
  const change = (e) => setForm({ ...form, [e.target.name]: e.target.value })
  async function submit(e) { e.preventDefault(); setBusy(true); setFormError(''); try { await api.createUser(form); setOpen(false); setForm(initial); reload() } catch (err) { setFormError(err.message) } finally { setBusy(false) } }
  return <><PageHeader eyebrow="Company hierarchy" title={user.role === 'OWNER' ? 'Employees' : 'Warehouse team'} description="Managers and employees remain assigned to exactly one warehouse." action={user.role === 'OWNER' && <button onClick={() => setOpen(true)} className="flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white"><Plus className="h-4 w-4" /> Add employee</button>} />{error && <p className="mb-4 text-red-600">{error}</p>}<DataTable rows={data ?? []} empty={loading ? 'Loading team…' : 'No employees found'} columns={[{ key: 'id', label: 'Employee ID', render: (v) => v?.slice(-8).toUpperCase() }, { key: 'first_name', label: 'Name', render: (_, r) => `${r.first_name} ${r.last_name}` }, { key: 'email', label: 'Email' }, { key: 'mobile', label: 'Phone' }, { key: 'role', label: 'Role', render: (v) => <StatusBadge value={v} /> }, { key: 'warehouse_id', label: 'Warehouse', render: (v) => warehouses.find((w) => w.id === v)?.warehouse_code ?? '—' }, { key: 'is_active', label: 'Status', render: (v) => <StatusBadge value={v ? 'ACTIVE' : 'INACTIVE'} /> }, { key: 'last_login', label: 'Last Login', render: (v) => v ? new Date(v).toLocaleString() : 'Never' }]} /><Modal title="Create employee" open={open} onClose={() => setOpen(false)}><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2">{formError && <p className="sm:col-span-2 text-sm text-red-600">{formError}</p>}<Field label="First name" name="first_name" value={form.first_name} onChange={change} /><Field label="Last name" name="last_name" value={form.last_name} onChange={change} /><Field label="Email" name="email" type="email" value={form.email} onChange={change} /><Field label="Phone" name="mobile" value={form.mobile} onChange={change} /><Field label="Temporary password" name="password" type="password" value={form.password} onChange={change} /><Select label="Role" name="role" value={form.role} onChange={change} options={['MANAGER', 'INBOUND', 'OUTBOUND'].map((value) => ({ value, label: value }))} /><div className="sm:col-span-2"><Select label="Warehouse" name="warehouse_id" value={form.warehouse_id} onChange={change} options={warehouses.map((w) => ({ value: w.id, label: `${w.warehouse_code} — ${w.name}` }))} /></div><div className="sm:col-span-2 flex justify-end"><SubmitButton busy={busy}>Create employee</SubmitButton></div></form></Modal></>
}
